[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
[rpc_endpoints]
local = "http://localhost:8545"
rpc = "http://localhost:8545"
redstone = "${PUBLIC_REDSTONE_URL}"

[profile.redstone.rpc_endpoints]
rpc = "${PUBLIC_REDSTONE_URL}"
